"""
Builder Helpers — Helper templates and component generators for Builder Agent.
Keeps agents/builder_agent.py lightweight (< 250 lines).
"""

import re
from pathlib import Path
from rich.console import Console

console = Console(legacy_windows=False)


def _safe_js_string(text: str, max_len: int = 100) -> str:
    """Sanitize text for embedding in generated JSX string literals."""
    if not text:
        return "Autonomous component generated by AI Agent Network."
    clean = text.split("=== PREVIOUS TEST")[0].split("=== END FAILURE")[0]
    clean = re.sub(r"[\r\n]+", " ", clean)
    clean = re.sub(r"[^\w\s.,\-/&]", "", clean)
    clean = clean.strip()
    if len(clean) > max_len:
        clean = clean[: max_len - 3] + "..."
    return clean or "Autonomous component generated by AI Agent Network."


def build_navbar(root_dir: Path, task_title: str, description: str):
    """Build or update Navbar component in frontend."""
    components_dir = root_dir / "frontend" / "src" / "components"
    components_dir.mkdir(parents=True, exist_ok=True)
    
    navbar_file = components_dir / "Navbar.jsx"
    navbar_code = '''import React from 'react';

export default function Navbar() {
  return (
    <header className="navbar">
      <div className="navbar-container">
        <div className="navbar-brand">
          <span className="logo-icon">⚡</span>
          <span className="logo-text">AI Analytics Dashboard</span>
        </div>
        <nav className="navbar-links">
          <a href="#overview" className="nav-link active">Overview</a>
          <a href="#analytics" className="nav-link">ML Analytics</a>
          <a href="#data" className="nav-link">Datasets</a>
          <a href="#agents" className="nav-link">Agent Network</a>
          <a href="#settings" className="nav-link">Settings</a>
        </nav>
        <div className="navbar-actions">
          <span className="status-badge live">● Live Agent Loop</span>
        </div>
      </div>
    </header>
  );
}
'''
    navbar_file.write_text(navbar_code, encoding="utf-8")
    console.print(f"[green]✅ Created Navbar component at {navbar_file}[/green]")

    # Check App.jsx and import Navbar if missing
    app_file = root_dir / "frontend" / "src" / "App.jsx"
    if app_file.exists():
        app_code = app_file.read_text(encoding="utf-8")
        if "Navbar" not in app_code:
            updated_app = "import Navbar from './components/Navbar';\n" + app_code
            if '<div className="app-container">' in updated_app:
                updated_app = updated_app.replace(
                    '<div className="app-container">',
                    '<div className="app-container">\n      <Navbar />'
                )
            elif "return (" in updated_app:
                updated_app = updated_app.replace(
                    "return (",
                    "return (\n    <>\n      <Navbar />"
                )
                if updated_app.endswith(";\n}") or updated_app.endswith("}"):
                    updated_app = updated_app.rstrip("}").rstrip("\n;").rstrip() + "\n    </>\n  );\n}"
            app_file.write_text(updated_app, encoding="utf-8")
            console.print("[green]✅ Integrated Navbar into App.jsx[/green]")

    test_dir = root_dir / "tests" / "unit"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file = test_dir / "test_navbar.py"
    test_code = '''"""Unit tests for Navbar component integration."""
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent

def test_navbar_file_exists():
    navbar_path = ROOT_DIR / "frontend" / "src" / "components" / "Navbar.jsx"
    assert navbar_path.exists(), "Navbar.jsx component file must exist"

def test_navbar_structure():
    navbar_path = ROOT_DIR / "frontend" / "src" / "components" / "Navbar.jsx"
    content = navbar_path.read_text(encoding="utf-8")
    assert "export default function Navbar" in content
    assert "AI Analytics Dashboard" in content
'''
    test_file.write_text(test_code, encoding="utf-8")


def build_warehouse_analytics(root_dir: Path, task_title: str, description: str):
    """Build or update Warehouse Analytics component in frontend."""
    components_dir = root_dir / "frontend" / "src" / "components"
    components_dir.mkdir(parents=True, exist_ok=True)
    
    warehouse_file = components_dir / "WarehouseAnalytics.jsx"
    warehouse_code = '''import React from 'react';

export default function WarehouseAnalytics() {
  return (
    <div className="warehouse-card card" style={{ marginTop: '20px' }}>
      <h3 style={{ fontSize: '18px', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '12px' }}>
        🏢 Warehouse Level Statistics & Metrics
      </h3>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px' }}>
        <div style={{ background: 'var(--bg-card)', padding: '12px', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
          <div style={{ color: 'var(--text-secondary)', fontSize: '12px' }}>Total Storage Utilized</div>
          <div style={{ fontSize: '20px', fontWeight: 700, color: 'var(--color-primary)' }}>84.2%</div>
        </div>
        <div style={{ background: 'var(--bg-card)', padding: '12px', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
          <div style={{ color: 'var(--text-secondary)', fontSize: '12px' }}>Active Units Streamed</div>
          <div style={{ fontSize: '20px', fontWeight: 700, color: '#34d399' }}>12,450</div>
        </div>
        <div style={{ background: 'var(--bg-card)', padding: '12px', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
          <div style={{ color: 'var(--text-secondary)', fontSize: '12px' }}>Processing Latency</div>
          <div style={{ fontSize: '20px', fontWeight: 700, color: '#c084fc' }}>18 ms</div>
        </div>
      </div>
    </div>
  );
}
'''
    warehouse_file.write_text(warehouse_code, encoding="utf-8")
    console.print(f"[green]✅ Created WarehouseAnalytics component at {warehouse_file}[/green]")

    dashboard_file = root_dir / "frontend" / "src" / "pages" / "Dashboard.jsx"
    if dashboard_file.exists():
        dash_code = dashboard_file.read_text(encoding="utf-8")
        if "WarehouseAnalytics" not in dash_code:
            updated_dash = "import WarehouseAnalytics from '../components/WarehouseAnalytics';\n" + dash_code
            if "</motion.div>" in updated_dash:
                updated_dash = updated_dash.replace("</motion.div>", "  <WarehouseAnalytics />\n    </motion.div>")
            dashboard_file.write_text(updated_dash, encoding="utf-8")

    test_dir = root_dir / "tests" / "unit"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file = test_dir / "test_warehouse_analytics.py"
    test_code = '''"""Unit tests for WarehouseAnalytics component."""
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent

def test_warehouse_file_exists():
    file_path = ROOT_DIR / "frontend" / "src" / "components" / "WarehouseAnalytics.jsx"
    assert file_path.exists(), "WarehouseAnalytics.jsx should exist"

def test_warehouse_structure():
    file_path = ROOT_DIR / "frontend" / "src" / "components" / "WarehouseAnalytics.jsx"
    content = file_path.read_text(encoding="utf-8")
    assert "Warehouse Level Statistics" in content
'''
    test_file.write_text(test_code, encoding="utf-8")


DATA_ANALYTICS_COMPONENT = '''import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import axios from 'axios'
import { Upload, Play, Brain, ExternalLink } from 'lucide-react'

const API = import.meta.env.VITE_API_URL || ''

export default function DataAnalytics() {
  const [uploading, setUploading] = useState(false)
  const [uploadMsg, setUploadMsg] = useState('')
  const [training, setTraining] = useState(false)
  const [trainResult, setTrainResult] = useState(null)

  const handleUpload = async (file) => {
    if (!file) return
    setUploading(true)
    setUploadMsg('')
    const formData = new FormData()
    formData.append('file', file)
    try {
      const res = await axios.post(`${API}/api/data/upload`, formData)
      setUploadMsg(`Uploaded ${res.data.rows} rows (${res.data.columns} columns)`)
    } catch {
      setUploadMsg('Upload failed — open ML Analytics for sample data')
    } finally {
      setUploading(false)
    }
  }

  const handleTrain = async () => {
    setTraining(true)
    setTrainResult(null)
    try {
      const res = await axios.post(`${API}/api/analytics/train`, {
        target_column: 'target',
        model_type: 'random_forest',
        n_estimators: 50,
        test_size: 0.2,
      })
      setTrainResult(res.data)
    } catch {
      setTrainResult(null)
    } finally {
      setTraining(false)
    }
  }

  const accuracy = trainResult?.results?.[0]?.accuracy

  return (
    <div id="data-analytics-panel" className="card" style={{ marginTop: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px', marginBottom: '16px' }}>
        <div>
          <h3 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
            Data Analytics
          </h3>
          <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginTop: '6px' }}>
            Upload CSV or Excel, train ML models, and explore results on the dashboard.
          </p>
        </div>
        <Link to="/analytics" style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '12px', fontWeight: 600, color: '#a78bfa', textDecoration: 'none' }}>
          Full ML Analytics <ExternalLink size={14} />
        </Link>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
        <div className="upload-zone" style={{ padding: '20px', cursor: 'pointer', textAlign: 'center' }}
          onClick={() => document.getElementById('dashboard-csv-input')?.click()}
          onDragOver={(e) => e.preventDefault()}
          onDrop={(e) => { e.preventDefault(); handleUpload(e.dataTransfer.files[0]) }}>
          <input id="dashboard-csv-input" type="file" accept=".csv,.xlsx,.xls" hidden
            onChange={(e) => handleUpload(e.target.files?.[0])} />
          {uploading ? <div className="spinner" style={{ margin: '0 auto' }} /> : (
            <>
              <Upload size={28} color="var(--color-primary-light)" style={{ margin: '0 auto 8px', display: 'block' }} />
              <p style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Drop CSV / Excel or click to upload</p>
              {uploadMsg && <p style={{ fontSize: '12px', color: 'var(--color-green)', marginTop: '8px' }}>{uploadMsg}</p>}
            </>
          )}
        </div>
        <div style={{ padding: '16px', background: 'var(--bg-primary)', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
            <Brain size={20} color="#a78bfa" />
            <span style={{ fontWeight: 600, fontSize: '14px', color: 'var(--text-primary)' }}>Quick Train</span>
          </div>
          <button type="button" className="btn btn-primary" style={{ width: '100%' }} onClick={handleTrain} disabled={training}>
            {training ? 'Training…' : (<><Play size={14} /> Train Random Forest</>)}
          </button>
          {accuracy != null && (
            <p style={{ fontSize: '12px', color: 'var(--color-green)', marginTop: '10px' }}>
              Accuracy: {(accuracy * 100).toFixed(1)}%
            </p>
          )}
        </div>
      </div>
    </div>
  )
}
'''

DATA_ANALYTICS_TEST = '''"""Unit tests for DataAnalytics component."""
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent

def test_dataanalytics_exists():
    file_path = ROOT_DIR / "frontend" / "src" / "components" / "DataAnalytics.jsx"
    assert file_path.exists(), "DataAnalytics.jsx component file must exist"

def test_dataanalytics_structure():
    content = (ROOT_DIR / "frontend/src/components/DataAnalytics.jsx").read_text(encoding="utf-8")
    assert "data-analytics-panel" in content
    assert "/api/data/upload" in content
    assert "/api/analytics/train" in content

def test_dataanalytics_on_dashboard():
    dash = (ROOT_DIR / "frontend/src/pages/Dashboard.jsx").read_text(encoding="utf-8")
    assert "DataAnalytics" in dash
    assert "<DataAnalytics" in dash
'''


def build_data_analytics(root_dir: Path) -> list:
    """Build Data Analytics panel — CSV/Excel upload + ML train on dashboard."""
    modified = []
    comp_file = root_dir / "frontend" / "src" / "components" / "DataAnalytics.jsx"
    comp_file.parent.mkdir(parents=True, exist_ok=True)
    existing = comp_file.read_text(encoding="utf-8") if comp_file.exists() else ""
    if existing != DATA_ANALYTICS_COMPONENT:
        comp_file.write_text(DATA_ANALYTICS_COMPONENT, encoding="utf-8")
        modified.append("DataAnalytics.jsx")
        console.print(f"[green]✅ Created/updated DataAnalytics at {comp_file}[/green]")

    dashboard = root_dir / "frontend" / "src" / "pages" / "Dashboard.jsx"
    if dashboard.exists():
        dash = dashboard.read_text(encoding="utf-8")
        updated = dash
        if "DataAnalytics" not in updated:
            updated = "import DataAnalytics from '../components/DataAnalytics'\n" + updated
        if "<DataAnalytics" not in updated and "AnomalyAlertPanel" in updated:
            updated = updated.replace(
                "<AnomalyAlertPanel",
                "{/* ── Data Analytics — CSV/Excel upload + ML training ── */}\n      <DataAnalytics />\n\n      <AnomalyAlertPanel",
                1,
            )
        if updated != dash:
            dashboard.write_text(updated, encoding="utf-8")
            modified.append("Dashboard.jsx")
            console.print("[green]✅ Wired DataAnalytics into Dashboard.jsx[/green]")

    test_file = root_dir / "tests" / "unit" / "test_dataanalytics.py"
    existing_test = test_file.read_text(encoding="utf-8") if test_file.exists() else ""
    if existing_test != DATA_ANALYTICS_TEST:
        test_file.write_text(DATA_ANALYTICS_TEST, encoding="utf-8")
        modified.append("test_dataanalytics.py")

    if not modified:
        console.print("[green]OK: Data Analytics task already applied in codebase[/green]")
        modified.append("already_applied")
    return modified


def build_dynamic_component(root_dir: Path, task_title: str, description: str):
    """Parse task title/description, create component, integrate into UI, and generate tests."""
    words = [w.capitalize() for w in "".join(c if c.isalnum() or c.isspace() else "" for c in task_title).split()]
    comp_name = "".join(words) or "DynamicComponent"
    
    components_dir = root_dir / "frontend" / "src" / "components"
    components_dir.mkdir(parents=True, exist_ok=True)
    
    comp_file = components_dir / f"{comp_name}.jsx"
    
    comp_code = f'''import React from 'react';

export default function {comp_name}() {{
  return (
    <div className="{comp_name.lower()}-card card" style={{{{ marginTop: '20px' }}}}>
      <h3 style={{{{ fontSize: '18px', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '12px' }}}}>
        ⚡ {task_title}
      </h3>
      <p style={{{{ color: 'var(--text-secondary)', fontSize: '14px', marginBottom: '16px' }}}}>
        {_safe_js_string(description)}
      </p>
      <div style={{{{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px' }}}}>
        <div style={{{{ background: 'var(--bg-card)', padding: '12px', borderRadius: '8px', border: '1px solid var(--border-color)' }}}}>
          <div style={{{{ color: 'var(--text-secondary)', fontSize: '12px' }}}}>Metric / Status</div>
          <div style={{{{ fontSize: '20px', fontWeight: 700, color: 'var(--color-primary)' }}}}>Active</div>
        </div>
      </div>
    </div>
  );
}}
'''
    comp_file.write_text(comp_code, encoding="utf-8")
    console.print(f"[green]✅ Created dynamic component {comp_name} at {comp_file}[/green]")

    test_dir = root_dir / "tests" / "unit"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file = test_dir / f"test_{comp_name.lower()}.py"
    test_code = f'''"""Unit tests for {comp_name} component."""
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent

def test_{comp_name.lower()}_exists():
    file_path = ROOT_DIR / "frontend" / "src" / "components" / "{comp_name}.jsx"
    assert file_path.exists(), "{comp_name}.jsx component file must exist"
'''
    test_file.write_text(test_code, encoding="utf-8")
    wire_component_to_dashboard(root_dir, comp_name)
    return comp_name


def wire_component_to_dashboard(root_dir: Path, comp_name: str) -> bool:
    """Import and render a component on the main Dashboard page."""
    dashboard = root_dir / "frontend" / "src" / "pages" / "Dashboard.jsx"
    if not dashboard.exists():
        return False
    dash = dashboard.read_text(encoding="utf-8")
    if f"<{comp_name}" in dash:
        return False
    updated = dash
    import_line = f"import {comp_name} from '../components/{comp_name}'\n"
    if comp_name not in updated:
        updated = import_line + updated
    anchor = "<DataAnalytics />"
    if anchor in updated:
        updated = updated.replace(
            anchor,
            f"{{/* ── {comp_name} sprint feature ── */}}\n      <{comp_name} />\n\n      {anchor}",
            1,
        )
    elif "<AnomalyAlertPanel" in updated:
        updated = updated.replace(
            "<AnomalyAlertPanel",
            f"{{/* ── {comp_name} sprint feature ── */}}\n      <{comp_name} />\n\n      <AnomalyAlertPanel",
            1,
        )
    else:
        return False
    if updated != dash:
        dashboard.write_text(updated, encoding="utf-8")
        console.print(f"[green]✅ Wired {comp_name} into Dashboard.jsx[/green]")
        return True
    return False
